# Use an official Maven image to build the Spring Boot app
FROM maven: 3.8.4-openjdk-17 As build
#Set the working directory
WORKDIR /app
# Copy the pom.xml and install dependencies
coPY pom. xml .
RUN mvn dependency: go-offline
# Copy the source code and build the application
COPY src ./src
RUN mvn clean patkage -DskipTests
# Use an official OpenJDK image to run the application
FROM openjdk:17-jdk-slim
#Set the working directory
WORKDIR / app
# Copy the built JAR file from the build stage
COPY --from=build /app/target/demo-0.0.1-SNAPSHOT.jar
# Expose port 8080
EXPOSE 8080
# Specify the command to run the application
ENTRYPOINT ["java", "-jar", "/app/notes-0.0.1-SNAPSHOT.jar"]